[variables]
GO_VERSION = "1.22"
NODE_VERSION = "20"

[languages]
go = true
node = "20"

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd server && go build -o location-server main.go"
]

[start]
cmd = "./server/location-server"